post:
  expiry:
    dayCount: '1'
mongodb:
  url: mongodb://localhost:27017
  path: mongodb+srv://user_dev:SNmPcspDHLI3BwAs@clusterfeed-9uqny.mongodb.net/test?retryWrites=true
  database:
    name: feedService2018